create extension if not exists pgcrypto;

create table if not exists public.scholarship_results (
  id bigint generated by default as identity primary key,
  scholarship_name text not null check (char_length(trim(scholarship_name)) between 2 and 160),
  country text not null check (char_length(trim(country)) between 2 and 120),
  study_level text not null,
  field_of_study text not null check (char_length(trim(field_of_study)) between 2 and 160),
  status text not null check (status in ('Applied', 'Interview', 'Waitlisted', 'Accepted', 'Rejected')),
  decision_date date not null,
  nationality text check (nationality is null or char_length(trim(nationality)) <= 120),
  gpa text check (gpa is null or char_length(trim(gpa)) <= 32),
  note text check (
    note is null
    or (
      char_length(note) <= 1200
      and note !~* '(https?://|www\.)'
    )
  ),
  hidden boolean not null default false,
  review_state text not null default 'approved' check (review_state in ('approved', 'pending', 'rejected')),
  moderation_reason text,
  fingerprint_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.scholarship_comments (
  id bigint generated by default as identity primary key,
  result_id bigint not null references public.scholarship_results(id) on delete cascade,
  text text not null check (
    char_length(trim(text)) between 1 and 400
    and text !~* '(https?://|www\.)'
  ),
  review_state text not null default 'approved' check (review_state in ('approved', 'pending', 'rejected')),
  moderation_reason text,
  fingerprint_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.verified_scholarships (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 2 and 160),
  source text not null default 'manual' check (source in ('database', 'manual')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.admin_users (
  email text primary key check (char_length(trim(email)) between 6 and 160),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists scholarship_results_created_at_idx on public.scholarship_results (created_at desc);
create index if not exists scholarship_results_name_idx on public.scholarship_results (scholarship_name);
create index if not exists scholarship_results_hidden_idx on public.scholarship_results (hidden);
create index if not exists scholarship_results_review_state_idx on public.scholarship_results (review_state);
create index if not exists scholarship_results_fingerprint_hash_idx on public.scholarship_results (fingerprint_hash);
create index if not exists scholarship_comments_result_id_idx on public.scholarship_comments (result_id);
create index if not exists scholarship_comments_review_state_idx on public.scholarship_comments (review_state);
create index if not exists scholarship_comments_fingerprint_hash_idx on public.scholarship_comments (fingerprint_hash);

alter table public.scholarship_results enable row level security;
alter table public.scholarship_comments enable row level security;
alter table public.verified_scholarships enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

grant execute on function public.current_user_is_admin() to anon, authenticated;

drop policy if exists "public can read scholarship results" on public.scholarship_results;
create policy "public can read scholarship results"
on public.scholarship_results
for select
to anon, authenticated
using (
  public.current_user_is_admin()
  or (
    review_state = 'approved'
    and not hidden
  )
);

drop policy if exists "public can submit scholarship results" on public.scholarship_results;

drop policy if exists "public can read scholarship comments" on public.scholarship_comments;
create policy "public can read scholarship comments"
on public.scholarship_comments
for select
to anon, authenticated
using (
  public.current_user_is_admin()
  or review_state = 'approved'
);

drop policy if exists "public can submit scholarship comments" on public.scholarship_comments;

drop policy if exists "public can read verified scholarships" on public.verified_scholarships;
create policy "public can read verified scholarships"
on public.verified_scholarships
for select
to anon, authenticated
using (true);

drop policy if exists "admins can read admin users" on public.admin_users;
create policy "admins can read admin users"
on public.admin_users
for select
to authenticated
using (public.current_user_is_admin());

insert into public.admin_users (email)
values ('admin@awaited.local')
on conflict (email) do nothing;

insert into public.verified_scholarships (name, source)
values
  ('Chevening Scholarship', 'database'),
  ('Fulbright Scholarship', 'database'),
  ('DAAD EPOS Scholarship', 'database'),
  ('Gates Cambridge Scholarship', 'database'),
  ('Erasmus Mundus Joint Masters', 'database'),
  ('Rhodes Scholarship', 'database'),
  ('Commonwealth Scholarship', 'database'),
  ('Australia Awards Scholarship', 'database'),
  ('MEXT Scholarship (Monbukagakusho)', 'database'),
  ('Türkiye Bursları (Turkey Scholarships)', 'database'),
  ('Korean Government Scholarship (KGSP/GKS)', 'database'),
  ('Chinese Government Scholarship (CSC)', 'database'),
  ('Swedish Institute Scholarship (SISS)', 'database'),
  ('New Zealand Scholarships (Manaaki)', 'database'),
  ('Aga Khan Foundation Scholarship', 'database'),
  ('Clarendon Scholarship', 'database'),
  ('Marshall Scholarship', 'database'),
  ('Schwarzman Scholars', 'database'),
  ('Mastercard Foundation Scholars Program', 'database'),
  ('Denys Holland Scholarship', 'database'),
  ('Stipendium Hungaricum', 'database'),
  ('Italian Government Scholarship', 'database'),
  ('Swiss Government Excellence Scholarship (ESKAS)', 'database'),
  ('Vanier Canada Graduate Scholarship', 'database'),
  ('Joint Japan/World Bank Graduate Scholarship (JJ/WBGSP)', 'database'),
  ('VLIR-UOS Scholarship', 'database'),
  ('DAAD Study Scholarship (General)', 'database'),
  ('Orange Knowledge Programme (OKP/Nuffic)', 'database'),
  ('Rotary Peace Fellowship', 'database'),
  ('Destination Australia Scholarship', 'database'),
  ('Organisation of American States (OAS) Scholarship', 'database'),
  ('African Union Mwalimu Nyerere Scholarship', 'database'),
  ('Adelaide Global Academic Excellence Scholarship', 'database'),
  ('Émile Boutmy Scholarship', 'database'),
  ('Eiffel Excellence Scholarship', 'database')
on conflict (name) do update
set source = case
  when public.verified_scholarships.source = 'manual' then public.verified_scholarships.source
  else excluded.source
end;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.scholarship_results;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.scholarship_comments;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.verified_scholarships;
    exception when duplicate_object then
      null;
    end;
  end if;
end $$;
