create extension if not exists pgcrypto;

create table if not exists public.scholarship_results (
  id bigint generated by default as identity primary key,
  scholarship_name text not null check (char_length(trim(scholarship_name)) between 2 and 160),
  country text not null check (char_length(trim(country)) between 2 and 120),
  study_level text not null,
  field_of_study text not null check (char_length(trim(field_of_study)) between 2 and 160),
  status text not null check (status in ('Applied', 'Interview', 'Waitlisted', 'Accepted', 'Rejected')),
  decision_date date not null,
  nationality text check (nationality is null or char_length(trim(nationality)) <= 120),
  gpa text check (gpa is null or char_length(trim(gpa)) <= 32),
  note text check (
    note is null
    or (
      char_length(note) <= 1200
      and note !~* '(https?://|www\.)'
    )
  ),
  hidden boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.scholarship_comments (
  id bigint generated by default as identity primary key,
  result_id bigint not null references public.scholarship_results(id) on delete cascade,
  text text not null check (
    char_length(trim(text)) between 1 and 400
    and text !~* '(https?://|www\.)'
  ),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.verified_scholarships (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 2 and 160),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists scholarship_results_created_at_idx on public.scholarship_results (created_at desc);
create index if not exists scholarship_results_name_idx on public.scholarship_results (scholarship_name);
create index if not exists scholarship_results_hidden_idx on public.scholarship_results (hidden);
create index if not exists scholarship_comments_result_id_idx on public.scholarship_comments (result_id);

alter table public.scholarship_results enable row level security;
alter table public.scholarship_comments enable row level security;
alter table public.verified_scholarships enable row level security;

drop policy if exists "public can read scholarship results" on public.scholarship_results;
create policy "public can read scholarship results"
on public.scholarship_results
for select
to anon, authenticated
using (true);

drop policy if exists "public can submit scholarship results" on public.scholarship_results;
create policy "public can submit scholarship results"
on public.scholarship_results
for insert
to anon, authenticated
with check (true);

drop policy if exists "public can read scholarship comments" on public.scholarship_comments;
create policy "public can read scholarship comments"
on public.scholarship_comments
for select
to anon, authenticated
using (true);

drop policy if exists "public can submit scholarship comments" on public.scholarship_comments;
create policy "public can submit scholarship comments"
on public.scholarship_comments
for insert
to anon, authenticated
with check (true);

drop policy if exists "public can read verified scholarships" on public.verified_scholarships;
create policy "public can read verified scholarships"
on public.verified_scholarships
for select
to anon, authenticated
using (true);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.scholarship_results;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.scholarship_comments;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.verified_scholarships;
    exception when duplicate_object then
      null;
    end;
  end if;
end $$;
