create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique check (char_length(trim(slug)) between 2 and 220),
  title text not null check (char_length(trim(title)) between 4 and 180),
  excerpt text check (excerpt is null or char_length(trim(excerpt)) <= 280),
  content text not null check (char_length(trim(content)) between 20 and 20000),
  published boolean not null default false,
  author_email text check (author_email is null or char_length(trim(author_email)) between 6 and 160),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.forum_threads (
  id bigint generated by default as identity primary key,
  slug text not null unique check (char_length(trim(slug)) between 2 and 220),
  title text not null check (char_length(trim(title)) between 4 and 160),
  body text not null check (
    char_length(trim(body)) between 10 and 2400
    and body !~* '(https?://|www\.)'
  ),
  locked boolean not null default false,
  review_state text not null default 'approved' check (review_state in ('approved', 'pending', 'rejected')),
  moderation_reason text,
  fingerprint_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.forum_replies (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.forum_threads(id) on delete cascade,
  body text not null check (
    char_length(trim(body)) between 1 and 1200
    and body !~* '(https?://|www\.)'
  ),
  review_state text not null default 'approved' check (review_state in ('approved', 'pending', 'rejected')),
  moderation_reason text,
  fingerprint_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists blog_posts_published_created_at_idx on public.blog_posts (published, created_at desc);
create index if not exists blog_posts_slug_idx on public.blog_posts (slug);
create index if not exists forum_threads_created_at_idx on public.forum_threads (created_at desc);
create index if not exists forum_threads_review_state_idx on public.forum_threads (review_state);
create index if not exists forum_threads_fingerprint_hash_idx on public.forum_threads (fingerprint_hash);
create index if not exists forum_replies_thread_id_idx on public.forum_replies (thread_id);
create index if not exists forum_replies_review_state_idx on public.forum_replies (review_state);
create index if not exists forum_replies_fingerprint_hash_idx on public.forum_replies (fingerprint_hash);

alter table public.blog_posts enable row level security;
alter table public.forum_threads enable row level security;
alter table public.forum_replies enable row level security;

drop policy if exists "public can read blog posts" on public.blog_posts;
create policy "public can read blog posts"
on public.blog_posts
for select
to anon, authenticated
using (
  public.current_user_is_admin()
  or published
);

drop policy if exists "public can read forum threads" on public.forum_threads;
create policy "public can read forum threads"
on public.forum_threads
for select
to anon, authenticated
using (
  public.current_user_is_admin()
  or review_state = 'approved'
);

drop policy if exists "public can submit forum threads" on public.forum_threads;

drop policy if exists "public can read forum replies" on public.forum_replies;
create policy "public can read forum replies"
on public.forum_replies
for select
to anon, authenticated
using (
  public.current_user_is_admin()
  or review_state = 'approved'
);

drop policy if exists "public can submit forum replies" on public.forum_replies;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.blog_posts;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.forum_threads;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.forum_replies;
    exception when duplicate_object then
      null;
    end;
  end if;
end $$;
