create table if not exists public.human_verification_sessions (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  fingerprint_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  last_used_at timestamptz not null default timezone('utc', now())
);

create index if not exists human_verification_sessions_fingerprint_hash_idx on public.human_verification_sessions (fingerprint_hash);
create index if not exists human_verification_sessions_expires_at_idx on public.human_verification_sessions (expires_at);

alter table public.human_verification_sessions enable row level security;
